version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/php

permissions:
  - object: /var/www/html/php
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: stop.sh
      timeout: 30
      runas: root
    - location: backup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start.sh
      timeout: 30
      runas: root
