version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - echo build started
      - pwd
      - ls
artifacts:
  files: 
    - '**/*'
